---
apiVersion: v1
kind: Service
metadata:
  name: gotalk-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gotalk-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  type: {{ .Values.api.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: gotalk-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gotalk-web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
  type: {{ .Values.web.service.type }}
