apiVersion: v2
name: gotalk
description: GoTalk Messenger Application - API + Web Frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - gotalk
  - messenger
  - chat
maintainers:
  - name: anhnq
    email: anhnq@anhnq.io.vn
